<?php
/**
 * Created by PhpStorm.
 * User: ly
 * Date: 2019/1/29
 * Time: 14:02
 */
namespace EasySwooleMiddleware\Middleware\Exception;

use Throwable;

class MiddlewareException extends \Exception
{
    public function __construct($message = "", $code = 0,Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);

    }

    public function serverExce(){
        $msg = <<<EOF
            errorMsg：{$this->message}
EOF;
        return $msg;
    }


    public function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
    }
}